services:
  dt-backend:
    container_name: dt-backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}

  dt-frontend:
    container_name: dt-frontend
    build:
      context: ./frontend
    depends_on:
      - dt-backend
